# -*- coding: utf-8 -*-
# Author Details :- Archana Nair, Manipal Institute of Technology, Reg No. 220928003
"""FastExponention.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14a2V7FyhZIIJViJKkv_bFI1Ryi8v48PH
"""

from pickle import STOP
import math
global ip,modulo,exp
y =1
# Fast exponentiation in congruences

def fastexp(a,b, n):
   global y
   while n>=1:
      r = n % 2 # get remainder using mod function2
      if r == 1:
         y = (a*y) % b # calculate y value when bit =1
      a = (a*a) % b # calculate a value 
      n =n // 2 # n get quotient value
      print(y , n , r)
   print(f"Fast exponentiation of {ip}^{exp} mod {modulo} is : ", y)
   y=1

# Input Data 

choice ="y" 
while choice == "y"or choice == "Y" or 1 :
     choice= input("Do you want to calculate fast exp value? Please enter Y/N : ")         
     if(choice=="Y" or choice=="y" ):
         ip,modulo,exp = int(input("Enter value of a in a^n mod b : ")) , int(input("Enter b in a^n mod b : ")) ,int(input("Enter power n in a^n mod b : "))
         fastexp(ip, modulo, exp)  
         continue
     elif choice=="n" or choice=="N":
          print("Stop calculating fast exp value.")
     else:
          print("Incorrect input! Please enter valid input.")
          continue
     break

