# -*- coding: utf-8 -*-

# Author Details :- Archana Nair, Manipal Institute of Technology, Reg No. 220928003
"""ModMultiplicativeInverse.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1w2cNzg-rs8oo0LMw3VpccqqWoVmLpe5k
"""

import math 
global r1 ,r2, t1, t2

#Modular Multiplicative Inverse

def multiinv(a,b):
    i=0
    r1 = b
    r2 = a
    t1, t2 = 0,1
    while r2 > 0 :
      remainder = r1 % r2 # get remainder
      q = r1 // r2 # get quotient 
      t = t1 - (q * t2) 
      r1 = r2
      r2 = remainder
      t1 = t2
      t2 = t
      i+= 1
      print(i,"interation values: ",r1 , r2, t1 , t2 , )
      if (t1 <0):
          inverse_modulo = t1 + t2
      else:
          inverse_modulo = t1
    print("inverse of",a,"mod",b,": ", inverse_modulo)
    return inverse_modulo

# numbers are co-prime or not
  
# Recursive function to
# return gcd of a and b

def __gcd(a, b):
  
    # Everything divides 0 
    if (a == 0 or b == 0): return 0
      
    # base case
    if (a == b): return a
      
    # a is greater
    if (a > b): 
        return __gcd(a - b, b)
              
    return __gcd(a, b - a)
  
# Function to check and print if 
# two numbers are co-prime or not 
def coprime(a, b):
      
    if ( __gcd(a, b) == 1):
        multiinv(a,b)
        print("Co-Prime")
    else:
        print("Not Co-Prime") 
         print("Cannot compute as numbers are not Co-prime")    
  

# Input for Modular multiplicative Inverse

choice = "yes" 
while choice == "y"or choice == "Y" or 1 :
      choice= input("Do you want to calculate modular multiplicative inverse value? Please enter Y/N : ")         
      if(choice=="Y" or choice=="y" ):
         a,b = int(input("Enter value of a in inverse of a mod b : ")) , int(input("Enter b in inverse of a mod b : "))
         coprime(a,b)        
         continue
      elif choice=="n" or choice=="N":
          print("Stop calculating modular multiplicative inverse value.")
      else:
          print("Incorrect input! Please enter valid input.")
          continue
      break